#  menu items

[[main]]
  name = "Debugging"
  weight = 1
  url = "debugging/"

[[main]]
  name = "Modules"
  weight = 2
  url = "modules/"

[[main]]
  name = "Git"
  weight = 3
  url = "git/"

[[main]]
  name = "Interactivity"
  weight = 4
  url = "events/"

[[main]]
  name = "API"
  weight = 5
  url = "events/"

[[main]]
  name = "React"
  weight = 6
  url = "events/"

[[main]]
  name = "Capstones"
  weight = 7
  url = "capstones/"
